# -*- coding: utf-8 -*-
"""IntegratedFinals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CVq-6tn1BcosvW8-8a_iCdlcNxeKsAQX
"""

#Functions for workspace of the arm

import pigpio
import time as t
pi = pigpio.pi()

def default():
    pi.set_servo_pulsewidth(18,2500)
    t.sleep(.5)
    pi.set_servo_pulsewidth(27,2500)
    t.sleep(.5)
    pi.set_servo_pulsewidth(17,2150)
    t.sleep(.5)
    pi.set_servo_pulsewidth(4,1670)

def throw():
    t.sleep(1)
    pi.set_servo_pulsewidth(18,2500)
    t.sleep(.5)
    pi.set_servo_pulsewidth(27,2500)
    t.sleep(.5)
    pi.set_servo_pulsewidth(17,2150)
    t.sleep(1)
    pi.set_servo_pulsewidth(18,2300)
    pi.set_servo_pulsewidth(27,600)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1400)
    t.sleep(.5)
    pi.set_servo_pulsewidth(4,1670)
    t.sleep(.5)
    pi.set_servo_pulsewidth(4,2250)
    default()
    t.sleep(1)


##############################################     A


def a1():
    pi.set_servo_pulsewidth(27,1930)
    pi.set_servo_pulsewidth(18,1800)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1600)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def a2():
    pi.set_servo_pulsewidth(27,1890)
    pi.set_servo_pulsewidth(18,1850)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1500)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a3():
    pi.set_servo_pulsewidth(27,1850)
    pi.set_servo_pulsewidth(18,1900)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1410)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a4():
    pi.set_servo_pulsewidth(27,1810)
    pi.set_servo_pulsewidth(18,1915)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1350)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a5():
    pi.set_servo_pulsewidth(27,1760)
    pi.set_servo_pulsewidth(18,1930)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1310)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a6():
    pi.set_servo_pulsewidth(27,1710)
    pi.set_servo_pulsewidth(18,1940)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1310)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a7():
    pi.set_servo_pulsewidth(27,1650)
    pi.set_servo_pulsewidth(18,1940)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1310)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a8():
    pi.set_servo_pulsewidth(27,1600)
    pi.set_servo_pulsewidth(18,1940)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1310)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a9():
    pi.set_servo_pulsewidth(27,1540)
    pi.set_servo_pulsewidth(18,1915)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1350)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a10():
    pi.set_servo_pulsewidth(27,1480)
    pi.set_servo_pulsewidth(18,1900)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1410)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a11():
    pi.set_servo_pulsewidth(27,1440)
    pi.set_servo_pulsewidth(18,1860)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1490)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def a12():
    pi.set_servo_pulsewidth(27,1400)
    pi.set_servo_pulsewidth(18,1800)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1600)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)


###############################################     B


def b1():
    pi.set_servo_pulsewidth(27,1940)
    pi.set_servo_pulsewidth(18,1875)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1430)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def b2():
    pi.set_servo_pulsewidth(27,1910)
    pi.set_servo_pulsewidth(18,1920)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1340)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b3():
    pi.set_servo_pulsewidth(27,1880)
    pi.set_servo_pulsewidth(18,1950)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1270)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b4():
    pi.set_servo_pulsewidth(27,1830)
    pi.set_servo_pulsewidth(18,1960)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1230)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b5():
    pi.set_servo_pulsewidth(27,1770)
    pi.set_servo_pulsewidth(18,1970)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1200)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b6():
    pi.set_servo_pulsewidth(27,1710)
    pi.set_servo_pulsewidth(18,1980)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1170)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b7():
    pi.set_servo_pulsewidth(27,1650)
    pi.set_servo_pulsewidth(18,1980)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1170)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b8():
    pi.set_servo_pulsewidth(27,1590)
    pi.set_servo_pulsewidth(18,1970)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1200)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b9():
    pi.set_servo_pulsewidth(27,1530)
    pi.set_servo_pulsewidth(18,1970)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1230)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b10():
    pi.set_servo_pulsewidth(27,1480)
    pi.set_servo_pulsewidth(18,1980)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1260)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b11():
    pi.set_servo_pulsewidth(27,1430)
    pi.set_servo_pulsewidth(18,1960)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1310)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def b12():
    pi.set_servo_pulsewidth(27,1390)
    pi.set_servo_pulsewidth(18,1940)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1380)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)


###############################################     C


def c1():
    pi.set_servo_pulsewidth(27,1980)
    pi.set_servo_pulsewidth(18,1930)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1300)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def c2():
    pi.set_servo_pulsewidth(27,1930)
    pi.set_servo_pulsewidth(18,1950)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1220)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c3():
    pi.set_servo_pulsewidth(27,1880)
    pi.set_servo_pulsewidth(18,1970)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1150)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c4():
    pi.set_servo_pulsewidth(27,1830)
    pi.set_servo_pulsewidth(18,1990)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1100)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c5():
    pi.set_servo_pulsewidth(27,1780)
    pi.set_servo_pulsewidth(18,2010)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1090)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c6():
    pi.set_servo_pulsewidth(27,1720)
    pi.set_servo_pulsewidth(18,2020)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1080)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c7():
    pi.set_servo_pulsewidth(27,1640)
    pi.set_servo_pulsewidth(18,2020)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1080)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c8():
    pi.set_servo_pulsewidth(27,1580)
    pi.set_servo_pulsewidth(18,2010)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1090)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c9():
    pi.set_servo_pulsewidth(27,1520)
    pi.set_servo_pulsewidth(18,2010)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1100)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c10():
    pi.set_servo_pulsewidth(27,1460)
    pi.set_servo_pulsewidth(18,2010)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1150)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def c11():
    pi.set_servo_pulsewidth(27,1400)
    pi.set_servo_pulsewidth(18,2000)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1200)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def c12():
    pi.set_servo_pulsewidth(27,1360)
    pi.set_servo_pulsewidth(18,1980)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1260)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)


###############################################     D


def d1():
    pi.set_servo_pulsewidth(27,2010)
    pi.set_servo_pulsewidth(18,1960)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1170)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def d2():
    pi.set_servo_pulsewidth(27,1970)
    pi.set_servo_pulsewidth(18,1990)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1100)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d3():
    pi.set_servo_pulsewidth(27,1930)
    pi.set_servo_pulsewidth(18,2020)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1080)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d4():
    pi.set_servo_pulsewidth(27,1880)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1000)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d5():
    pi.set_servo_pulsewidth(27,1810)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1000)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d6():
    pi.set_servo_pulsewidth(27,1730)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1000)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d7():
    pi.set_servo_pulsewidth(27,1650)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,990)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d8():
    pi.set_servo_pulsewidth(27,1570)
    pi.set_servo_pulsewidth(18,2060)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,990)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d9():
    pi.set_servo_pulsewidth(27,1490)
    pi.set_servo_pulsewidth(18,2060)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1020)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d10():
    pi.set_servo_pulsewidth(27,1410)
    pi.set_servo_pulsewidth(18,2055)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1050)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d11():
    pi.set_servo_pulsewidth(27,1360)
    pi.set_servo_pulsewidth(18,2050)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1090)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
def d12():
    pi.set_servo_pulsewidth(27,1330)
    pi.set_servo_pulsewidth(18,2020)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1130)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)


###############################################     E


def e1():
    pi.set_servo_pulsewidth(27,2050)
    pi.set_servo_pulsewidth(18,1990)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1100)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def e2():
    pi.set_servo_pulsewidth(27,2010)
    pi.set_servo_pulsewidth(18,2020)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1020)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e3():
    pi.set_servo_pulsewidth(27,1970)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,990)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e4():
    pi.set_servo_pulsewidth(27,1900)
    pi.set_servo_pulsewidth(18,2050)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,950)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e5():
    pi.set_servo_pulsewidth(27,1820)
    pi.set_servo_pulsewidth(18,2060)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,920)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e6():
    pi.set_servo_pulsewidth(27,1730)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,900)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e7():
    pi.set_servo_pulsewidth(27,1650)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,900)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e8():
    pi.set_servo_pulsewidth(27,1570)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,900)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e9():
    pi.set_servo_pulsewidth(27,1480)
    pi.set_servo_pulsewidth(18,2080)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,930)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e10():
    pi.set_servo_pulsewidth(27,1400)
    pi.set_servo_pulsewidth(18,2080)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,960)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e11():
    pi.set_servo_pulsewidth(27,1320)
    pi.set_servo_pulsewidth(18,2080)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1020)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def e12():
    pi.set_servo_pulsewidth(27,1270)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1040)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)


###############################################     F


def f1():
    pi.set_servo_pulsewidth(27,2100)
    pi.set_servo_pulsewidth(18,2010)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,1030)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def f2():
    pi.set_servo_pulsewidth(27,2050)
    pi.set_servo_pulsewidth(18,2030)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,960)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f3():
    pi.set_servo_pulsewidth(27,2000)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,910)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f4():
    pi.set_servo_pulsewidth(27,1930)
    pi.set_servo_pulsewidth(18,2050)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,870)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f5():
    pi.set_servo_pulsewidth(27,1860)
    pi.set_servo_pulsewidth(18,2060)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,830)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f6():
    pi.set_servo_pulsewidth(27,1740)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,830)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f7():
    pi.set_servo_pulsewidth(27,1610)
    pi.set_servo_pulsewidth(18,2080)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,820)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f8():
    pi.set_servo_pulsewidth(27,1500)
    pi.set_servo_pulsewidth(18,2080)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,840)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f9():
    pi.set_servo_pulsewidth(27,1400)
    pi.set_servo_pulsewidth(18,2100)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,870)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f10():
    pi.set_servo_pulsewidth(27,1320)
    pi.set_servo_pulsewidth(18,2100)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,890)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f11():
    pi.set_servo_pulsewidth(27,1260)
    pi.set_servo_pulsewidth(18,2100)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,930)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def f12():
    pi.set_servo_pulsewidth(27,1200)
    pi.set_servo_pulsewidth(18,2100)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,980)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)


###############################################     G


def g1():
    pi.set_servo_pulsewidth(27,2150)
    pi.set_servo_pulsewidth(18,2030)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,980)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def g2():
    pi.set_servo_pulsewidth(27,2100)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,920)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g3():
    pi.set_servo_pulsewidth(27,2050)
    pi.set_servo_pulsewidth(18,2050)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,860)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g4():
    pi.set_servo_pulsewidth(27,1980)
    pi.set_servo_pulsewidth(18,2060)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,820)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g5():
    pi.set_servo_pulsewidth(27,1900)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,780)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g6():
    pi.set_servo_pulsewidth(27,1800)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,740)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g7():
    pi.set_servo_pulsewidth(27,1630)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,740)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g8():
    pi.set_servo_pulsewidth(27,1500)
    pi.set_servo_pulsewidth(18,2090)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,770)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g9():
    pi.set_servo_pulsewidth(27,1360)
    pi.set_servo_pulsewidth(18,2100)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,800)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g10():
    pi.set_servo_pulsewidth(27,1260)
    pi.set_servo_pulsewidth(18,2120)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,840)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g11():
    pi.set_servo_pulsewidth(27,1200)
    pi.set_servo_pulsewidth(18,2120)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,880)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def g12():
    pi.set_servo_pulsewidth(27,1150)
    pi.set_servo_pulsewidth(18,2120)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,950)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)


###############################################     H


def h1():
    pi.set_servo_pulsewidth(27,2220)
    pi.set_servo_pulsewidth(18,2040)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,950)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

def h2():
    pi.set_servo_pulsewidth(27,2190)
    pi.set_servo_pulsewidth(18,2050)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,880)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h3():
    pi.set_servo_pulsewidth(27,2140)
    pi.set_servo_pulsewidth(18,2050)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,820)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h4():
    pi.set_servo_pulsewidth(27,2080)
    pi.set_servo_pulsewidth(18,2060)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,760)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h5():
    pi.set_servo_pulsewidth(27,1970)
    pi.set_servo_pulsewidth(18,2060)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,720)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h6():
    pi.set_servo_pulsewidth(27,1850)
    pi.set_servo_pulsewidth(18,2070)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,700)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h7():
    pi.set_servo_pulsewidth(27,1640)
    pi.set_servo_pulsewidth(18,2080)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,700)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h8():
    pi.set_servo_pulsewidth(27,1430)
    pi.set_servo_pulsewidth(18,2110)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,720)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h9():
    pi.set_servo_pulsewidth(27,1280)
    pi.set_servo_pulsewidth(18,2130)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,740)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h10():
    pi.set_servo_pulsewidth(27,1190)
    pi.set_servo_pulsewidth(18,2130)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,780)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h11():
    pi.set_servo_pulsewidth(27,1130)
    pi.set_servo_pulsewidth(18,2130)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,840)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)
    
def h12():
    pi.set_servo_pulsewidth(27,1080)
    pi.set_servo_pulsewidth(18,2130)
    t.sleep(1)
    pi.set_servo_pulsewidth(17,910)
    t.sleep(1)
    pi.set_servo_pulsewidth(4,2250)

#To call the function required
def callBox(boxes):
    default()
    globals()[boxes]()
    throw()


#To find which function to call
def findBox(x,y):
    str1 = "";
    str2 = "";
    xc = 620/12
    yc = 414/8
    if(x < 0 or y < 0):
        print("Invalid")
        exit(0)
    else:
        if(x < 12*xc):
            str2 = "12"
            if(x < 11*xc):
                str2 = "11"
                if(x < 10*xc):
                    str2 = "10"
                    if(x < 9*xc):
                        str2 = "9"
                        if(x < 8*xc):
                            str2 = "8"
                            if(x < 7*xc):
                                str2 = "7"
                                if(x < 6*xc):
                                    str2 = "6"
                                    if(x < 5*xc):
                                        str2 = "5"
                                        if(x < 4*xc):
                                            str2 = "4"
                                            if(x < 3*xc):
                                                str2 = "3"
                                                if(x < 2*xc):
                                                    str2 = "2"
                                                    if(x < xc):
                                                        str2 = "1"
        if(y < 8*yc):
            str1 = "h"
            if(y < 7*yc):
                str1 = "g"
                if(y < 6*yc):
                    str1 = "f"
                    if(y < 5*yc):
                        str1 = "e"
                        if(y < 4*yc):
                            str1 = "d"
                            if(y < 3*yc):
                                str1 = "c"
                                if(y < 2*yc):
                                    str1 = "b"
                                    if(y < yc):
                                        str1 = "a"
        box = str1+str2;
        print(box)
        return(box)

from google.colab import drive
drive.mount('/content/drive')

#To get coordinates of the the object which is detected first
def getCoordinates():
    mid_x = [0]
    mid_y = [0]

    file = open('result.txt', 'r')
    for i, line in enumerate(file):
        if i >= 5:
            lst = line.split()
            if lst[0] == 'Plastic':
                x = int(lst[4])
                y = int(lst[6])
                w = int(lst[8])
                h = int(lst[10].replace(')', ''))
            else:
                x = int(lst[3])
                y = int(lst[5])
                w = int(lst[7])
                h = int(lst[9].replace(')', ''))
            mx = float(x + w/2)
            my = float(y - h/2)
            mid_x.append(mx)
            mid_y.append(my)

    print(mid_x)
    print(mid_y)

    return(mid_x,mid_y)

#To crop the image to the working space of arm
def crop(img):
    crp_img = img[143:557,327:947]
    #cv2.imshow("img",crp_img);
    #cv2.imwrite("Crop.jpg",crp_img)
    return(crp_img)

#MAIN function which loops until all objects are sorted
import cv2
import os

from picamera import PiCamera
from time import sleep

pi.set_servo_pulsewidth(4,0)
pi.set_servo_pulsewidth(17,0)
pi.set_servo_pulsewidth(18,0)
pi.set_servo_pulsewidth(27,0)
default()

camera = PiCamera()
camera.capture("trial.jpg")
im = cv2.imread("trial.jpg")
img = crop(im)
cv2.imwrite("test.jpg",img)
    

#Darknet command
os.system("./darknet detector test data/obj.data cfg/yolov3-tiny-test.cfg backup/yolov3-tiny-demo.weights -dont_show -ext_output test.jpg > result.txt")
mid_x,mid_y = getCoordinates()

count = len(mid_x);
for c in range(count):
    #Find box where the coordinates is present
    box = findBox(mid_x[c],mid_y[c])
    #Call function to call the box
    callBox(box)
    
print("Done")